[[session]]
name = "default"
path = "~"
startup_command = ""

[[session]]
name = " nvim config"
path = "~/.config/nvim"
startup_command = "nvim ."

[[session]]
name = "󰙵 tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "󱇝 sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = " alacritty config"
path = "~/.config/alacritty"
startup_command = "nvim alacritty.toml"

[[session]]
name = " Home"
path = "~"
startup_command = "ls -p"

[[session]]
name = " zsh config"
path = "~"
startup_command = "nvim .zshrc"

[[session]]
name = "󰅩 Dev"
path = "~/Programming/"
startup_command = "ls -p"
