import = ["~/.config/alacritty/colors/catppuccin_mocha.toml"]
live_config_reload = true

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Full"
opacity = 0.95
blur = true
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
dynamic_title = true
option_as_alt = "Both"

[font]
size = 16.0
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[mouse]
hide_when_typing = true

[cursor]
unfocused_hollow = true

# Note: C-a (prefix) is \u0001
[[keyboard.bindings]]
chars = "\u0001f"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

# add more bindings from time to time...
