# Set tmux to true color
set-option -sa terminal-overrides ", xterm*: Tc"
set -g mouse on

# Reload config 
bind r source-file ~/.config/tmux/tmux.conf \; display ".tmux.conf reloaded!"

# Set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# More intuitive split commands
unbind %
bind h split-window -h -c "#{pane_current_path}"
unbind '"'
bind v split-window -v -c "#{pane_current_path}"

# Also open new windows in cwd
bind c new-window -c "#{pane_current_path}"

# more intuitive keybindings for splitting
unbind %
bind h split-window -h
unbind '"'
bind v split-window -v

# easier window movement
unbind [
# bind N prev
# unsure about these, but let's try them for a while
bind [ prev
bind ] next

unbind n
bind n new-window

# Kill windows and panes without confirmation
bind-key X kill-window
bind-key x kill-pane

# set vi keys
bind Escape copy-mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# run tmux sessionizer (modified ThePrimeagen script)
bind-key -r f run-shell "tmux neww '~/.config/tmux/tmux-sessionizer.sh'"

# Rename session
bind-key , command-prompt -I "#S" "rename-session '%%'"

# Activate Tmux Plugin Manager
set -g @plugin 'tmux-plugins/tpm'
# Activate more sensible defaults
set -g @plugin 'tmux-plugins/tmux-sensible'
# vim / tmux navigation
set -g @plugin 'christoomey/vim-tmux-navigator'
# the superior color scheme
set -g @plugin 'catppuccin/tmux'
# copy with y (VIM SUPREMACY)
set -g @plugin 'tmux-plugins/tmux-yank'

# starting at 0 is cool, but for keyboard control 1 is better
set -g base-index 1
set -g pane-base-index 1 
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Catppuccin config
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_default_text "#W | #{b:pane_current_path}"
set -g @catppuccin_window_current_text "#W | #{b:pane_current_path}"

set -g @catppuccin_status_modules_right "directory application session"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_directory_color "#fab387"
set -g @catppuccin_directory_text "#{pane_current_path}"

# Status bar background transparent
set-option -g status-style bg=default

# Run TPM
# Note: Install new plugins with <C-a>I
run '~/.config/tmux/plugins/tpm/tpm'

